#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const HERE=path.dirname(fileURLToPath(import.meta.url)),ROOT=path.resolve(HERE,'..'),OUT=path.join(ROOT,'qa-results');fs.mkdirSync(OUT,{recursive:true});const errors=[],warnings=[];
function walk(d){let a=[];for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['.git','node_modules','qa-results'].includes(e.name))continue;const p=path.join(d,e.name);a=e.isDirectory()?a.concat(walk(p)):a.concat(p)}return a}
const htmlFiles=walk(ROOT).filter(f=>f.endsWith('.html'));const enginePages=[];const ids=new Map();
for(const f of htmlFiles){const s=fs.readFileSync(f,'utf8');const m=s.match(/window\.BM_ANALYTICS_CONFIG\s*=\s*\{([^}]+)\}/);if(!m)continue;const body=m[1],course=(body.match(/course\s*:\s*["']([^"']+)/)||[])[1]||'',id=(body.match(/engineId\s*:\s*["']([^"']+)/)||[])[1]||'',gv=(body.match(/generatorVersion\s*:\s*["']([^"']+)/)||[])[1]||'';const rel=path.relative(ROOT,f).replaceAll(path.sep,'/');enginePages.push({rel,course,id,gv});if(!course)errors.push(`${rel}: empty analytics course`);if(!id)errors.push(`${rel}: empty analytics engineId`);if(!gv)errors.push(`${rel}: empty generatorVersion`);if(id){if(ids.has(id))errors.push(`duplicate engineId ${id}: ${ids.get(id)} and ${rel}`);else ids.set(id,rel)}if(!s.includes('G-377MTFXSF3'))errors.push(`${rel}: GA4 tag ID missing`);if(!s.includes('/assets/problem-tracking.js')&&!s.includes('assets/problem-tracking.js'))errors.push(`${rel}: problem-tracking.js missing`);let hasGenerated=/BMAnalytics\?*\.problemGenerated\s*\(/.test(s)||s.includes('/assets/ap-topic-practice.js');if(!hasGenerated){for(const sm of s.matchAll(/<script[^>]+src=[\"']([^\"']+)[\"']/gi)){let src=sm[1].split('?')[0];if(!src.endsWith('.js')||/^https?:/i.test(src))continue;const fp=src.startsWith('/')?path.join(ROOT,src.slice(1)):path.resolve(path.dirname(f),src);if(fs.existsSync(fp)&&/BMAnalytics\?*\.problemGenerated\s*\(/.test(fs.readFileSync(fp,'utf8'))){hasGenerated=true;break;}}}if(!hasGenerated)errors.push(`${rel}: no visible problemGenerated instrumentation path`);}
if(enginePages.length!==89)errors.push(`expected 89 instrumented practice engines, found ${enginePages.length}`);

// Static API misuse guard across all first-party source files.
const sourceFiles=walk(ROOT).filter(f=>/\.(?:html|js)$/.test(f)&&!f.startsWith(path.join(ROOT,'tools')+path.sep)&&!f.startsWith(path.join(ROOT,'.github')+path.sep));let checkedCalls=0;
for(const f of sourceFiles){const s=fs.readFileSync(f,'utf8'),rel=path.relative(ROOT,f).replaceAll(path.sep,'/');if(/BMAnalytics\?*\.answerCorrect\s*\(/.test(s))errors.push(`${rel}: calls nonexistent BMAnalytics.answerCorrect()`);for(const m of s.matchAll(/BMAnalytics\?*\.answerChecked\s*\(([^\n;]*)/g)){checkedCalls++;const call=m[1];if(/^[^,]+,\s*\{/.test(call))errors.push(`${rel}: answerChecked second argument appears to be an object instead of a boolean: ${call.slice(0,150)}`);}}

// Dynamic contract test for problem-tracking.js.
const tracker=fs.readFileSync(path.join(ROOT,'assets/problem-tracking.js'),'utf8');
function storage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function makeSandbox({online=true,withGtag=true}={}){const events=[],localStorage=storage(),sessionStorage=storage();const doc={body:null,visibilityState:'visible',getElementById(){return null},createElement(){return {setAttribute(){},style:{},innerHTML:'',appendChild(){},addEventListener(){}}},addEventListener(){}};const window={BM_ANALYTICS_CONFIG:{course:'ap_calculus_ab',engineId:'qa_engine',generatorVersion:'99'},location:{search:''},addEventListener(){},BatchMathRepro:{noteProblem(){}},gtag:withGtag?((...a)=>events.push(a)):undefined};const sb={window,document:doc,navigator:{onLine:online},localStorage,sessionStorage,URLSearchParams,console,setTimeout:()=>0,clearTimeout:()=>{},Date,JSON,Object,String,Number,Array,Math};vm.createContext(sb);vm.runInContext(tracker,sb,{filename:'problem-tracking.js'});return{sb,events,localStorage,sessionStorage};}
try{
 const {sb,events}=makeSandbox();const p={id:'qa-1',problemType:'qa_type',problemVariant:'qa_variant'};sb.window.BMAnalytics.ensurePracticeStarted({practice_mode:'qa'});sb.window.BMAnalytics.problemGenerated(p,{practice_mode:'qa'});sb.window.BMAnalytics.answerChecked(p,false,{practice_mode:'qa'});let names=events.filter(x=>x[0]==='event').map(x=>x[1]);if(names.filter(x=>x==='answer_checked').length!==1||names.includes('answer_correct'))errors.push('tracking contract: incorrect answer emitted wrong event set');let checked=events.find(x=>x[0]==='event'&&x[1]==='answer_checked')?.[2];if(checked?.answer_result!=='incorrect')errors.push(`tracking contract: incorrect answer_result was ${checked?.answer_result}`);events.length=0;sb.window.BMAnalytics.answerChecked(p,true,{practice_mode:'qa'});names=events.filter(x=>x[0]==='event').map(x=>x[1]);if(names.join(',')!=='answer_checked,answer_correct')errors.push(`tracking contract: correct answer events were ${names.join(',')}`);checked=events.find(x=>x[1]==='answer_checked')?.[2];if(checked?.problem_type!=='qa_type'||checked?.problem_variant!=='qa_variant')errors.push('tracking contract: explicit problem metadata was not preserved');
 const off=makeSandbox({online:false,withGtag:false});off.sb.window.BMAnalytics.problemGenerated(p);if(off.sb.window.BMAnalytics.queuedCount()!==1)errors.push('tracking contract: offline event did not queue');off.sb.navigator.onLine=true;off.sb.window.gtag=(...a)=>off.events.push(a);await off.sb.window.BMAnalytics.flush();if(off.sb.window.BMAnalytics.queuedCount()!==0)errors.push('tracking contract: offline queue did not flush');const ev=off.events.find(x=>x[0]==='event'&&x[1]==='problem_generated');if(ev?.[2]?.offline_queued!=='yes')errors.push('tracking contract: flushed event missing offline_queued=yes');
}catch(e){errors.push(`dynamic tracker contract test failed: ${e.stack||e.message}`)}

// Shared topic pages must set problem metadata before emission.
const shared=fs.readFileSync(path.join(ROOT,'assets/ap-topic-practice.js'),'utf8');for(const token of ['current.problemType=activeSlug','current.problemVariant=current.variant','current.generatorVersion=cfg.generatorVersion','problemGenerated(current','answerChecked(current,ok'])if(!shared.includes(token))errors.push(`ap-topic-practice.js missing analytics contract token: ${token}`);

const report={ok:errors.length===0,generatedAt:new Date().toISOString(),instrumentedEngines:enginePages.length,uniqueEngineIds:ids.size,answerCheckedCallSites:checkedCalls,warnings,errors,engines:enginePages};fs.writeFileSync(path.join(OUT,'analytics-qa.json'),JSON.stringify(report,null,2)+'\n');const lines=['BatchMath analytics instrumentation QA',`Result: ${report.ok?'PASS':'FAIL'}`,`Instrumented engines: ${enginePages.length}`,`Unique engine IDs: ${ids.size}`,`answerChecked call sites audited: ${checkedCalls}`,`Warnings: ${warnings.length}`,...warnings.map(x=>'- '+x),`Errors: ${errors.length}`,...errors.map(x=>'- '+x),''];fs.writeFileSync(path.join(OUT,'analytics-qa.txt'),lines.join('\n'));console.log(lines.join('\n'));if(errors.length)process.exit(1);
